CLIPMENU_VERSION="0.1.0"
CLIPMENU_DIR="${CLIPMENU_DIR:-$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd)}"
CLIPMENU_BACKEND="${CLIPMENU_BACKEND:-hyprland}"

source "$CLIPMENU_DIR/lib/backends/$CLIPMENU_BACKEND.sh"

CLIPMENU_FZF_PROMPT="${CLIPMENU_FZF_PROMPT:-clipboard > }"
CLIPMENU_FZF_PREVIEW_OPTS="${CLIPMENU_FZF_PREVIEW_OPTS:-right:65%:wrap:border-left}"
CLIPMENU_WINDOW_CLASS="${CLIPMENU_WINDOW_CLASS:-fuzzel}"
CLIPMENU_WINDOW_TITLE="${CLIPMENU_WINDOW_TITLE:-Clipboard}"
CLIPMENU_MONITOR_RATIO="${CLIPMENU_MONITOR_RATIO:-0.5}"
CLIPMENU_AUTOPASTE="${CLIPMENU_AUTOPASTE:-true}"
CLIPMENU_AUTOPASTE_DELAY="${CLIPMENU_AUTOPASTE_DELAY:-0.5}"
