CLIPY_VERSION="0.1.0"
CLIPY_DIR="${CLIPY_DIR:-$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd)}"
CLIPY_BACKEND="${CLIPY_BACKEND:-hyprland}"

source "$CLIPY_DIR/lib/backends/$CLIPY_BACKEND.sh"

CLIPY_FZF_PROMPT="${CLIPY_FZF_PROMPT:- clipy > }"
CLIPY_FZF_PREVIEW_OPTS="${CLIPY_FZF_PREVIEW_OPTS:-right:55%:wrap:border}"
CLIPY_WINDOW_CLASS="${CLIPY_WINDOW_CLASS:-fuzzel}"
CLIPY_WINDOW_TITLE="${CLIPY_WINDOW_TITLE:-Clipboard}"
CLIPY_MONITOR_RATIO="${CLIPY_MONITOR_RATIO:-0.5}"
CLIPY_AUTOPASTE="${CLIPY_AUTOPASTE:-true}"
CLIPY_AUTOPASTE_DELAY="${CLIPY_AUTOPASTE_DELAY:-0.5}"
